CREATE USER 'oppia'@'%' IDENTIFIED BY 'oppia';
GRANT ALL PRIVILEGES ON oppia.* TO 'oppia'@'%';

CREATE USER IF NOT EXISTS 'root'@'%' IDENTIFIED BY 'root';
GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;
